### ISSUE TITLE
总是报错‘UNABLE_TO_VERIFY_LEAF_SIGNATURE’

### ISSUE THREAD

**Issue by lon91ong** [bc0042/sheep-solver#13]
如题，开始安装时就报这个错，参考[stackoverflow](https://stackoverflow.com/questions/20747817/error-unable-to-verify-leaf-signature-phonegap-installation)的方法，用`npm config set strict-ssl false`后安装成功了

但到后面下载地图数据再次报错：
```
sheep-solver-master>node util/get map
https://cat-match-static.easygame2021.com/maps/a5be795ede173877fe211275bd855b77.txt
AxiosError: unable to verify the first certificate
    at AxiosError.from (file:///F:/sheep-solver-master/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///F:/WorkSpace/python/sheep-solver-master/node_modules/axios/lib/adapters/http.js:515:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (F:\sheep-solver-master\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Host: '',
      Connection: 'keep-alive',
      xweb_xhr: '1',
      t: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzEyNDM2NzgsInVpZCI6MTIyOTQ2NjU4LCJ2ZXIiOiIxIiwiZXh0IjoiMzYzMzMyNjMzMTY0MzU2NDMyMzg2MzY0MzkzNjM5NjIzMzY1NjUzOTM0MzMzMDYxIiwiY29kZSI6IjNkNGU3OTczODdhNWY3NjE5YWMyOGRlNGVhZjg4MDIwIiwiZW5kIjoxNjcxMjQzNjc4NzM5LCJwbGEiOjF9.7D-9f-EnefBlZCxOM9LeyuAITYrd26-LVCtcanlns5g',
      'user-agent': 'Mozilla/5.0 (Linux; Android 9; MI 9 Build/PQ3A.190705.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Safari/537.36 MicroMessenger/8.0.2.1860(0x28000234) Process/appbrand1 WeChat/arm32 Weixin Android Tablet NetType/WIFI Language/zh_CN ABI/arm64 MiniProgramEnv/android',
      'Content-Type': 'application/json',
      Accept: '*/*',
      'Sec-Fetch-Site': 'cross-site',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      Referer: 'https://servicewechat.com/wx141bfb9b73c970a9/34/page-frame.html',
      'Accept-Language': 'en-us,en',
      'Accept-Encoding': 'gzip, deflate',
      [Symbol(defaults)]: [Object]
    },
    method: 'get',
    url: 'https://cat-match-static.easygame2021.com/maps/a5be795ede173877fe211275bd855b77.txt',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
......
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://cat-match-static.easygame2021.com/maps/a5be795ede173877fe211275bd855b77.txt',
    [Symbol(kCapture)]: false
  },
  cause: Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)
      at TLSSocket.emit (node:events:513:28)
      at TLSSocket._finishInit (node:_tls_wrap:952:8)
      at ssl.onhandshakedone (node:_tls_wrap:733:12) {
    code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
  }
}

Node.js v18.12.0
```

怀疑时Node版本适配的问题，可是大佬用的18.11.7版本在[Node Releases List](https://nodejs.org/en/download/releases/)里面都找不到

求大佬指点

另外希望大佬能用个LTS的Node版本，比如18.12.0

**Comment by bc0042** [comment]
cause: Error: unable to verify the first certificate
证书问题，你是不是开着什么抓包软件在跑？关了试一下

**Comment by lon91ong** [comment]
一针见血，果然是抓包工具的问题，关了就正常了
