### ISSUE TITLE
这个问题是为什么，大佬我未找到

### ISSUE THREAD

**Issue by 351535126** [bc0042/sheep-solver#16]
PS C:\Users\33885\Downloads\sheep-solver-master\sheep-solver-master> node util/send game2.json
node:internal/modules/cjs/loader:400
      const err = new Error(
                  ^

Error: Cannot find module 'C:\Users\33885\Downloads\sheep-solver-master\sheep-solver-master\node_modules\@protobufjs\inquire\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:400:19)
    at Module._findPath (node:internal/modules/cjs/loader:613:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\33885\Downloads\sheep-solver-master\sheep-solver-master\node_modules\protobufjs\src\util\minimal.js:17:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\33885\\Downloads\\sheep-solver-master\\sheep-solver-master\\node_modules\\@protobufjs\\inquire\\package.json',
  requestPath: '@protobufjs/inquire'
}

**Comment by 351535126** [comment]
这是算出来结果之后，提交上不去就显示这个

**Comment by 351535126** [comment]
options: 0
269,268,267,266,265,264,258,263,262,253,261,257,256,260,255,252,259,254,249,251,250,239,248,246,244,247,242,229,245,241,231,243,237,99,240,236,220,238,235,225,234,232,211,233,230,204,228,227,221,226,224,206,223,222,219,218,217,214,216,215,199,213,212,207,210,209,176,208,201,185,205,198,177,203,200,158,202,193,188,197,196,195,194,187,166,192,184,168,191,182,181,190,180,160,189,172,165,186,59,47,183,171,157,170,169,93,164,159,151,167,150,145,179,178,58,163,156,149,155,153,139,45,44,34,174,33,19,175,46,12,161,35,20,162,36,21,173,98,37,138,133,126,154,152,9,148,147,144,146,141,136,142,127,92,143,135,131,140,82,8,137,130,76,134,128,83,132,124,123,66,60,48,125,120,38,121,114,23,113,112,108,115,101,22,109,102,11,129,103,95,122,87,77,117,67,10,100,94,84,119,118,111,116,110,106,105,104,-4,-1,110,107,97,96,88,86,61,79,49,39,91,85,71,90,81,78,89,74,68,109,69,63,104,75,65,118,70,57,80,53,52,56,43,32,72,40,25,73,64,62,31,26,24,51,18,6,50,41,27,105,28,15,54,16,2,100,3,1,55,42,30,29,17,14,13,7,5,4,0
save game2.json
success <<<<<<<<<<<<<<<<
PS C:\Users\33885\Downloads\sheep-solver-master\sheep-solver-master> node util/send game2.json
node:internal/modules/cjs/loader:400
      const err = new Error(
                  ^

Error: Cannot find module 'C:\Users\33885\Downloads\sheep-solver-master\sheep-solver-master\node_modules\@protobufjs\inquire\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:400:19)
    at Module._findPath (node:internal/modules/cjs/loader:613:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\33885\Downloads\sheep-solver-master\sheep-solver-master\node_modules\protobufjs\src\util\minimal.js:17:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\33885\\Downloads\\sheep-solver-master\\sheep-solver-master\\node_modules\\@protobufjs\\inquire\\package.json',
  requestPath: '@protobufjs/inquire'
